let recipes=[];
const els={q:document.querySelector('#q'),genre:document.querySelector('#genre'),category:document.querySelector('#category'),minutes:document.querySelector('#minutes'),rating:document.querySelector('#rating'),sort:document.querySelector('#sort'),list:document.querySelector('#recipeList'),count:document.querySelector('#count'),clear:document.querySelector('#clearFilters'),dialog:document.querySelector('#recipeDialog'),content:document.querySelector('#dialogContent'),close:document.querySelector('#closeDialog')};
function keyRating(id){return 'recipe-rating:'+id} function keyNote(id){return 'recipe-note:'+id}
function getRating(id){return Number(localStorage.getItem(keyRating(id))||0)} function getNote(id){return localStorage.getItem(keyNote(id))||''}
function fillSelect(el,values){[...new Set(values)].sort().forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;el.appendChild(o)})}
function normalize(s){return String(s||'').toLowerCase().replace(/\s+/g,'')}
function matches(r){const q=normalize(els.q.value);const hay=normalize([r.title,r.genre,r.category,r.summary,...(r.ingredients_tags||[]),...(r.feature_tags||[]),...(r.ingredients||[])].join(' '));if(q&&!hay.includes(q))return false;if(els.genre.value&&r.genre!==els.genre.value)return false;if(els.category.value&&r.category!==els.category.value)return false;if(els.minutes.value&&Number(r.minutes)>Number(els.minutes.value))return false;if(els.rating.value){const rt=getRating(r.id);if(els.rating.value==='unrated'){if(rt!==0)return false}else if(rt<Number(els.rating.value))return false}return true}
function render(){let list=recipes.filter(matches);if(els.sort.value==='rating')list.sort((a,b)=>getRating(b.id)-getRating(a.id)||a.title.localeCompare(b.title,'ja'));else if(els.sort.value==='minutes')list.sort((a,b)=>Number(a.minutes)-Number(b.minutes)||a.title.localeCompare(b.title,'ja'));else list.sort((a,b)=>a.title.localeCompare(b.title,'ja'));els.count.textContent=list.length+'件表示 / 全'+recipes.length+'件';els.list.innerHTML='';list.forEach(r=>{const card=document.createElement('article');card.className='card';const rating=getRating(r.id);card.innerHTML='<h2>'+escapeHtml(r.title)+'</h2><div class="meta">'+escapeHtml(r.genre)+' ｜ '+escapeHtml(r.category)+' ｜ 約'+r.minutes+'分 ｜ '+escapeHtml(r.servings)+'</div><p>'+escapeHtml(r.summary)+'</p><div class="tags">'+(r.ingredients_tags||[]).slice(0,5).map(t=>'<span class="tag">'+escapeHtml(t)+'</span>').join('')+'</div><div class="rating-line">'+(rating?'★ '+rating+'/10':'未評価')+'</div>';card.addEventListener('click',()=>openRecipe(r));els.list.appendChild(card)})}
function openRecipe(r){const rating=getRating(r.id),note=getNote(r.id);els.content.innerHTML='<article class="detail"><h2>'+escapeHtml(r.title)+'</h2><div class="meta">'+escapeHtml(r.genre)+' ｜ '+escapeHtml(r.category)+' ｜ 約'+r.minutes+'分 ｜ '+escapeHtml(r.servings)+'</div><p class="summary">'+escapeHtml(r.summary)+'</p><h3>材料</h3><ul>'+r.ingredients.map(x=>'<li>'+escapeHtml(x)+'</li>').join('')+'</ul><h3>下準備</h3><ol>'+r.prep.map(x=>'<li>'+escapeHtml(x)+'</li>').join('')+'</ol><h3>調理手順</h3><ol>'+r.steps.map(x=>'<li>'+escapeHtml(x)+'</li>').join('')+'</ol><h3>失敗しないポイント</h3><ul>'+r.points.map(x=>'<li>'+escapeHtml(x)+'</li>').join('')+'</ul><h3>追加すると美味しい食材・アレンジ</h3><ul>'+r.arrangements.map(x=>'<li>'+escapeHtml(x)+'</li>').join('')+'</ul><div class="userbox"><h3>自分の評価・メモ</h3><div class="stars">'+Array.from({length:10},(_,i)=>{const n=i+1;return '<button data-rating="'+n+'" class="'+(rating===n?'active':'')+'">★'+n+'</button>'}).join('')+'</div><textarea id="memoArea" placeholder="次回変えたい点、家族の反応、分量調整など">'+escapeHtml(note)+'</textarea><button class="save-note" id="saveNote">メモを保存</button></div></article>';els.content.querySelectorAll('[data-rating]').forEach(btn=>btn.addEventListener('click',()=>{localStorage.setItem(keyRating(r.id),btn.dataset.rating);openRecipe(r);render()}));els.content.querySelector('#saveNote').addEventListener('click',()=>{localStorage.setItem(keyNote(r.id),els.content.querySelector('#memoArea').value);const b=els.content.querySelector('#saveNote');b.textContent='保存しました';setTimeout(()=>b.textContent='メモを保存',900)});if(!els.dialog.open)els.dialog.showModal()}
function escapeHtml(str){return String(str).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]))}
['input','change'].forEach(evt=>[els.q,els.genre,els.category,els.minutes,els.rating,els.sort].forEach(el=>el.addEventListener(evt,render)));
els.clear.addEventListener('click',()=>{els.q.value='';els.genre.value='';els.category.value='';els.minutes.value='';els.rating.value='';els.sort.value='title';render()});els.close.addEventListener('click',()=>els.dialog.close());els.dialog.addEventListener('click',e=>{if(e.target===els.dialog)els.dialog.close()});
fetch('recipes.json').then(r=>r.json()).then(data=>{recipes=data;fillSelect(els.genre,recipes.map(r=>r.genre));fillSelect(els.category,recipes.map(r=>r.category));render()}).catch(err=>{els.count.textContent='recipes.json の読み込みに失敗しました。';console.error(err)});